// Copyright LetsGo. All Rights Reserved.

#include "K2Node/K2Node_GameEventBase.h"

#include "BlueprintActionDatabaseRegistrar.h"
#include "BlueprintNodeSpawner.h"
#include "GameEventNodeUtils.h"
#include "EdGraph/EdGraphPin.h"
#include "GameplayTagContainer.h"
#include "GameEventTypes.h"

#define LOCTEXT_NAMESPACE "UK2Node_GameEventBase"

const FName UK2Node_GameEventBase::FGameEventBasePinNames::EventIdTypePinName(TEXT("EventIdType"));
const FName UK2Node_GameEventBase::FGameEventBasePinNames::EventTagPinName(TEXT("EventTag"));
const FName UK2Node_GameEventBase::FGameEventBasePinNames::EventStringPinName(TEXT("EventName"));

UK2Node_GameEventBase::UK2Node_GameEventBase()
{
}

void UK2Node_GameEventBase::PinDefaultValueChanged(UEdGraphPin* Pin)
{
	Super::PinDefaultValueChanged(Pin);

	if (Pin && IsEventIdentifierPin(Pin))
	{
		UpdatePinVisibility();
	}
}

FText UK2Node_GameEventBase::GetMenuCategory() const
{
	return NSLOCTEXT("K2Node", "GameEventCategory", "GameEventSystem");
}

FText UK2Node_GameEventBase::GetKeywords() const
{
	return NSLOCTEXT("K2Node", "GameEventBase_Keywords", "event game system");
}

void UK2Node_GameEventBase::PostReconstructNode()
{
	Super::PostReconstructNode();
	UpdatePinVisibility();
}

void UK2Node_GameEventBase::GetMenuActions(FBlueprintActionDatabaseRegistrar& ActionRegistrar) const
{
	const UClass* ActionKey = GetClass();

	if (ActionRegistrar.IsOpenForRegistration(ActionKey))
	{
		UBlueprintNodeSpawner* NodeSpawner = UBlueprintNodeSpawner::Create(GetClass());
		check(NodeSpawner != nullptr);

		ActionRegistrar.AddBlueprintAction(ActionKey, NodeSpawner);
	}
}

void UK2Node_GameEventBase::UpdatePinVisibility()
{
	UEdGraphPin* EventTagPin = GetEventTagPin();
	UEdGraphPin* EventStringPin = GetEventStringPin();

	if (!EventTagPin || !EventStringPin)
	{
		return;
	}

	if (UGameEventNodeUtils::IsStringEventId(GetEventIdTypePin()))
	{
		UGameEventNodeUtils::ClearPinValue(EventTagPin);
		EventTagPin->bHidden = true;
		EventStringPin->bHidden = false;
	}
	else
	{
		UGameEventNodeUtils::ClearPinValue(EventStringPin);
		EventTagPin->bHidden = false;
		EventStringPin->bHidden = true;
	}

	GetGraph()->NotifyGraphChanged();
}

FString UK2Node_GameEventBase::GetCurrentEventName() const
{
	return UGameEventNodeUtils::GetCurrentEventName(GetEventIdTypePin(), GetEventTagPin(), GetEventStringPin());
}

void UK2Node_GameEventBase::CreateEventIdentifierPins()
{
	const UEdGraphSchema_K2* K2Schema = GetDefault<UEdGraphSchema_K2>();

	UEnum* EventIdTypeEnum = StaticEnum<EEventIdType>();
	UEdGraphPin* EventIdTypePin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Byte, EventIdTypeEnum, FGameEventBasePinNames::EventIdTypePinName);
	K2Schema->SetPinAutogeneratedDefaultValueBasedOnType(EventIdTypePin);

	CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Struct, FGameplayTag::StaticStruct(), FGameEventBasePinNames::EventTagPinName);

	CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_String, FGameEventBasePinNames::EventStringPinName);
}

UEdGraphPin* UK2Node_GameEventBase::GetEventIdTypePin() const
{
	UEdGraphPin* Pin = FindPin(FGameEventBasePinNames::EventIdTypePinName);
	check(Pin == nullptr || Pin->Direction == EGPD_Input);
	return Pin;
}

UEdGraphPin* UK2Node_GameEventBase::GetEventTagPin() const
{
	UEdGraphPin* Pin = FindPin(FGameEventBasePinNames::EventTagPinName);
	check(Pin == nullptr || Pin->Direction == EGPD_Input);
	return Pin;
}

UEdGraphPin* UK2Node_GameEventBase::GetEventStringPin() const
{
	UEdGraphPin* Pin = FindPin(FGameEventBasePinNames::EventStringPinName);
	check(Pin == nullptr || Pin->Direction == EGPD_Input);
	return Pin;
}

bool UK2Node_GameEventBase::IsEventIdentifierPin(const UEdGraphPin* Pin) const
{
	if (!Pin)
	{
		return false;
	}

	return Pin->PinName == FGameEventBasePinNames::EventIdTypePinName ||
	       Pin->PinName == FGameEventBasePinNames::EventTagPinName ||
	       Pin->PinName == FGameEventBasePinNames::EventStringPinName;
}

#undef LOCTEXT_NAMESPACE
